export const OUTFITS = [
  { id: 'A', name: '허름한 나시' },
  { id: 'B', name: '동정 파괴자 스웨터' },
  { id: 'C', name: '메이드' },
  { id: 'D', name: '바니걸' },
  { id: 'E', name: '알몸' },
  { id: 'F', name: '비키니' },
];

export const POSES = [
  { id: 1, name: '진지' },
  { id: 2, name: '부끄' },
  { id: 3, name: '폭소' },
  { id: 4, name: '당황' },
  { id: 5, name: '놀람' },
  { id: 6, name: '유혹' },
  { id: 7, name: '눈물' },
  { id: 8, name: '분노' },
  { id: 9, name: '정상위1' },
  { id: 10, name: '정상위2' },
  { id: 11, name: '정상위3' },
  { id: 12, name: '파이즈리1' },
  { id: 13, name: '파이즈리2' },
  { id: 14, name: '파이즈리3' },
  { id: 15, name: '펠라1' },
  { id: 16, name: '펠라2' },
  { id: 17, name: '펠라3' },
  { id: 18, name: '핸드잡1' },
  { id: 19, name: '핸드잡2' },
  { id: 20, name: '핸드잡3' },
  { id: 21, name: '리버스 카우걸1' },
  { id: 22, name: '리버스 카우걸2' },
  { id: 23, name: '리버스 카우걸3' },
  { id: 24, name: '후배위1' },
  { id: 25, name: '후배위2' },
  { id: 26, name: '후배위3' },
  { id: 27, name: '에프터 펠라치오1' },
  { id: 28, name: '에프터 펠라치오2' },
  { id: 29, name: '에프터 펠라치오3' },
  { id: 30, name: '핑거링1' },
  { id: 31, name: '핑거링2' },
  { id: 32, name: '핑거링3' },
  { id: 33, name: '커닐링구스1' },
  { id: 34, name: '커닐링구스2' },
  { id: 35, name: '커닐링구스3' },
  { id: 36, name: '이라마치오1' },
  { id: 37, name: '이라마치오2' },
  { id: 38, name: '이라마치오3' },
  { id: 39, name: '절정1' },
  { id: 40, name: '절정2' },
  { id: 41, name: '절정3' },
  { id: 42, name: '풋잡1' },
  { id: 43, name: '풋잡2' },
  { id: 44, name: '풋잡3' },
  { id: 45, name: '수유대딸1' },
  { id: 46, name: '수유대딸2' },
  { id: 47, name: '수유대딸3' },
  { id: 48, name: '들박1' },
  { id: 49, name: '들박2' },
  { id: 50, name: '들박3' },
  { id: 51, name: '풀넬슨1' },
  { id: 52, name: '풀넬슨2' },
  { id: 53, name: '풀넬슨3' },
  { id: 54, name: '측위1' },
  { id: 55, name: '측위2' },
  { id: 56, name: '측위3' },
  { id: 57, name: '여성상위1' },
  { id: 58, name: '여성상위2' },
  { id: 59, name: '여성상위3' }
];

export const getImageUrl = (outfitCode: string, num: number) => {
  return `https://pub-aeb2f7e4efda4c1a8c09ace152744942.r2.dev/${outfitCode}/${num}.jpg`;
};
